"""Synthetic pair corpus (A2s) — stage-1 training data, ADR 0001 addendum П3.

Public surface: :func:`cortex.synth.generate.generate_corpus` plus the types,
strategy registry, prompt constants, sample-quota math and
serialization/fingerprint helpers. The module is NETWORK-FREE — the LLM enters
only as an injected callback. See docs/synth.md for commands and the П3
discipline.
"""

from cortex.synth.generate import (
    BODY_RATIO_MAX,
    BODY_RATIO_MIN,
    LABEL_DUPLICATE,
    LABEL_NOT_DUPLICATE,
    LLM_STRATEGIES,
    MARKER_LINE_RE,
    MARKER_PREFIX_RE,
    MAX_ATTEMPTS,
    MAX_TITLE_CHARS,
    MIN_BODY_CHARS,
    MIN_TITLE_CHARS,
    NEAR_TOPIC_PROMPT_EN,
    NEAR_TOPIC_PROMPT_RU,
    PARAPHRASE_PROMPT_EN,
    PARAPHRASE_PROMPT_RU,
    PROMPT_VERSION,
    STRATEGIES,
    STRATEGY_BROKEN_FIELD,
    STRATEGY_NEAR_TOPIC,
    STRATEGY_PARAPHRASE,
    STRATEGY_TRIVIAL_NEGATIVE,
    TOPICS,
    VARIANT_LINE_EN,
    VARIANT_LINE_RU,
    SynthPair,
    SynthRecord,
    SynthStats,
    SynthTopic,
    SynthTopicError,
    corpus_fingerprint_of_pairs,
    fingerprint_object,
    generate_corpus,
    label_name,
    manifest_bytes_of_pairs,
    manifest_entries,
    pair_row,
    pair_row_json,
    parse_llm_record,
    sample_quotas,
    strip_protocol_markers,
    validate_candidate,
)

__all__ = [
    "BODY_RATIO_MAX",
    "BODY_RATIO_MIN",
    "LABEL_DUPLICATE",
    "LABEL_NOT_DUPLICATE",
    "LLM_STRATEGIES",
    "MARKER_LINE_RE",
    "MARKER_PREFIX_RE",
    "MAX_ATTEMPTS",
    "MAX_TITLE_CHARS",
    "MIN_BODY_CHARS",
    "MIN_TITLE_CHARS",
    "NEAR_TOPIC_PROMPT_EN",
    "NEAR_TOPIC_PROMPT_RU",
    "PARAPHRASE_PROMPT_EN",
    "PARAPHRASE_PROMPT_RU",
    "PROMPT_VERSION",
    "STRATEGIES",
    "STRATEGY_BROKEN_FIELD",
    "STRATEGY_NEAR_TOPIC",
    "STRATEGY_PARAPHRASE",
    "STRATEGY_TRIVIAL_NEGATIVE",
    "TOPICS",
    "VARIANT_LINE_EN",
    "VARIANT_LINE_RU",
    "SynthPair",
    "SynthRecord",
    "SynthStats",
    "SynthTopic",
    "SynthTopicError",
    "corpus_fingerprint_of_pairs",
    "fingerprint_object",
    "generate_corpus",
    "label_name",
    "manifest_bytes_of_pairs",
    "manifest_entries",
    "pair_row",
    "pair_row_json",
    "parse_llm_record",
    "sample_quotas",
    "strip_protocol_markers",
    "validate_candidate",
]
